# Generated by Django 3.0.7 on 2023-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emri_produktit', models.CharField(max_length=255)),
                ('modeli', models.CharField(max_length=255)),
                ('ngjyra', models.CharField(max_length=255)),
                ('qmimi', models.IntegerField()),
                ('fotografia', models.ImageField(upload_to='foto/%Y/%m/%d/')),
                ('foto1', models.ImageField(blank=True, upload_to='foto/%Y/%m/%d/')),
                ('foto2', models.ImageField(blank=True, upload_to='foto/%Y/%m/%d/')),
                ('foto3', models.ImageField(blank=True, upload_to='foto/%Y/%m/%d/')),
                ('foto4', models.ImageField(blank=True, upload_to='foto/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
