# Generated by Django 3.0.7 on 2023-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produktet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ekrani',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kartela_grafike',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lloji',
            field=models.CharField(choices=[('L', 'Laptop'), ('M', 'Monitor')], default='L', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='memoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='procesori',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rami',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
