# Generated by Django 3.0.7 on 2023-04-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produktet', '0002_auto_20230415_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lloji_i_panelit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pesha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rezolucion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
