# Generated by Django 3.0.7 on 2023-04-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produktet', '0004_auto_20230416_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lloji_panelit',
            field=models.CharField(blank=True, choices=[('IPS', 'IPS'), ('VA', 'VA'), ('TN', 'TN'), ('OLED', 'OLED')], max_length=10),
        ),
    ]
