# Generated by Django 3.0.7 on 2023-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=255)),
                ('mbiemri', models.CharField(max_length=255)),
                ('pozita', models.CharField(max_length=255)),
                ('fotografia', models.ImageField(upload_to='foto/%Y/%m/%d')),
            ],
        ),
    ]
