# Generated by Django 3.0.7 on 2023-04-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fotografia',
            field=models.ImageField(upload_to='foto/%Y/%m/%d/'),
        ),
    ]
